### ISSUE TITLE
[feature]: Add arm64 support

### ISSUE THREAD

**Issue by jpdante** [torbenraab/plane#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Thanks for your efforts in maintaining such a crucial feature free.

I've been trying to test out your fork but I think some of your containers are missing support for arm64, currently I have an Oracle Cloud arm based server and I can't try to use it.

Do you have any plans on adding support for arm64 on your docker images?
I think the only image missing arm64 support is `plane-frontend`

### Why should this be worked on?

The original plane repository already supports arm64, so I think adding support for it would be easy.

**Comment by poudelprakash** [comment]
@torbenraab core team has arm64 support in the major branches, it is now just a matter of code sync.

**Comment by torbenraab** [comment]
Hay, already working on it. Code is in sync but I'm having problems building the image via GitHub actions. Also tried with a self-hosted agent

**Comment by torbenraab** [comment]
fixed in #19
