### ISSUE TITLE
[update]: This fork is way behind the actual plane repo, request to make it upto date please

### ISSUE THREAD

**Issue by kotasudhakar** [torbenraab/plane#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This fork is way behind the actual plane repo.
I deeply request you @torbenraab to make it up to date please as will be missing out on all the latest features, if you can.
Or can you please guide me on doing it, so that i can do the changes and raise a PR.  

### Why should this be worked on?

This fork is way behind the actual plane repo, request to make it upto date please as will be missing out on all the latest features

**Comment by torbenraab** [comment]
Currently updating to v0.22 and pulling for preview soon
