### ISSUE TITLE
[bug]: cannot pull docker images

### ISSUE THREAD

**Issue by leoms1408** [torbenraab/plane#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to pull the docker images using "docker compose --env-file plane.env pull" I get the following error:

```shell
[+] Pulling 13/13
✔ worker Skipped - Image is already present locally
✔ plane-redis Skipped - Image is already present locally
✔ space Skipped - Image is already present locally
✔ api Skipped - Image is already present locally 
✔ plane-db Skipped - Image is already present locally
✔ admin Skipped - Image is already present locally
✔ web Skipped - Image is already present locally
✔ beat-worker Skipped - Image is already present locally
✔ proxy Skipped - Image is already present locally
✔ migrator Skipped - Image is already present locally
✘ plane-minio Error                 context canceled
✘ plane-mq Error                    context canceled
✘ live Error                         denied
``` 

### Steps to reproduce

Follow the instructions for Latest release here:
https://github.com/torbenraab/plane/tree/preview/deploy/selfhost

### Environment

Production

### Browser

None

### Variant

Self-hosted

### Version

v0.23.1

**Comment by torbenraab** [comment]
Thanks for the input! The issue should be resolved by now. There was a package which was still private.
